name: CI Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest

    container:
      image: gradle:8.0.2

    services:
      selenium:
        image: selenium/standalone-chrome-debug:3.11.0-californium

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gradle tests
        working-directory: ./tests
        run: gradle test