name: CI Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest

    container:
      image: gradle:8.0.2

    services:
      selenium:
        image: selenium/standalone-chrome:3.141.59

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Navigate to tests directory
        run: cd tests

      - name: Run Gradle tests
        run: gradle test