name: CI Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest

    container:
      image: gradle:8.0.2

    services:
      selenium:
        image: selenium/standalone-chrome:4.18.1
        env:
          SE_SCREEN_WIDTH: 1920
          SE_SCREEN_HEIGHT: 1080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install curl
        run: apt-get update && apt-get install -y curl
        
      - name: Wait for Selenium
        run: |
          echo "Waiting for Selenium..."
          for i in {1..10}; do
            if curl -sSf http://selenium:4444 >/dev/null; then
              echo "Selenium ready!"
              exit 0
            fi
            sleep 3
          done
          echo "Selenium not ready in time!" >&2
          exit 1

      - name: Run Gradle tests
        working-directory: ./tests
        run: gradle clean build test --info
