name: CI Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit_test:
    runs-on: ubuntu-latest

    container:
      image: gradle:8.0.2

    services:
      selenium:
        image: selenium/standalone-chrome:4.18.1
        env:
          SE_SCREEN_WIDTH: 1920
          SE_SCREEN_HEIGHT: 1080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gradle tests
        working-directory: ./tests
        run: gradle clean build test --info
